version: '3.7'

services:
  postgres:
    image: 'postgres:15.1'
    container_name: 'database'
    ports:
      - 5433:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=postgres'